name: Install Node modules

description: Validate a project when using Zero-Installs.

inputs:
  working-directory:
    description: Folder to install packages in (e.g., ./client or ./server)
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm install