name: Node.js CI

on:
  push:
    branches: [main,develop] # Trigger the workflow on every commit to the main and develop branch.
  pull_request:
    branches: [main,develop] # Trigger the workflow on pull requests targeting the main and develop branch

env:
  node-version: 21.x
  working-directory: ./client

jobs:
  format:
    name: Run linting & formatting
    runs-on: ubuntu-latest

    concurrency:
      group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
      cancel-in-progress: true

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.node-version }}

      - name: Install Client Dependencies
        uses: ./.github/actions/install-node-modules
        with:
          working-directory: ./client

      - name: Format Client
        uses: ./.github/actions/format-code
        with:
          working-directory: ./client

      - name: Install Server Dependencies
        uses: ./.github/actions/install-node-modules
        with:
          working-directory: ./server

      - name: Format Server
        uses: ./.github/actions/format-code
        with:
          working-directory: ./server



  test:
    name: Run type checking & tests
    needs: format
    runs-on: ubuntu-latest

    concurrency:
      group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }} - ${{ matrix.node-version }}"
      cancel-in-progress: true

    defaults:
      run:
        working-directory: ./client

    strategy:
      matrix:
        node-version: [21x]

    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v5

      - name: Use Node.js ${{ env.node-version }}
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.node-version }}

      - name: Install Node modules
        uses: ./.github/actions/install-node-modules
        with:
          working-directory: ./client

      - name: Run tests using the vitest framework
        uses: ./.github/actions/run-tests
        with:
          working-directory: ./client

  build:
    name: Builds the app
    needs: test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5 # Step 1: Check out the source code from the repository.

      - name: Use Node.js ${{ env.node-version }}
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.node-version }}

      - name: Install Client Dependencies
        uses: ./.github/actions/install-node-modules
        with:
            working-directory: ./client
  
      - name: Build Client
        uses: ./.github/actions/build-app
        with:
          working-directory: ./client
  
      - name: Install Server Dependencies
        uses: ./.github/actions/install-node-modules
        with:
          working-directory: ./server
  
      - name: Build Server
        uses: ./.github/actions/build-app
        with:
          working-directory: ./server
